name: "Energy Planner"
version: "0.1.20"
slug: "energy_planner"
description: "LP-based energy optimization"
arch:
  - amd64
  # - aarch64
url: "https://github.com/avsaase/energy-planner"
ingress: true
ingress_port: 8099
homeassistant_api: true
panel_icon: "mdi:battery-charging"
panel_title: "Energy Planner"
image: "ghcr.io/avsaase/{arch}-energy-planner"
init: false
options:
  solar_forecast_entities:
    - "sensor.energy_production_today_2"
    - "sensor.energy_production_tomorrow_2"
  electricity_price_entity: "sensor.frank_energie_prijzen_huidige_elektriciteit_inkoopprijs"
  battery_parameters:
    capacity_wh: 5120
    lifetime_cycles: 6000
    purchase_cost_eur: 1200
    max_charge_power_w: 2500
    max_discharge_power_w: 2500
    charge_efficiency: 0.88
    discharge_efficiency: 0.88
    min_soc_percent: 0.1
    max_soc_percent: 1.0
  electricity_price_parameters:
    supplier_cost_import_eur_per_kwh: 0.0182
    supplier_cost_export_eur_per_kwh: 0.0182
    energy_tax_import_eur_per_kwh: 0.09161
    energy_tax_export_eur_per_kwh: 0.0
    vat_import: 0.21
    vat_export: 0.0
  current_gross_consumption_power_entity: "sensor.gross_power_consumption"
schema:
  solar_forecast_entities:
    - str
  electricity_price_entity: str
  battery_parameters:
    capacity_wh: float
    lifetime_cycles: int
    purchase_cost_eur: float
    max_charge_power_w: float
    max_discharge_power_w: float
    charge_efficiency: float
    discharge_efficiency: float
    min_soc_percent: float
    max_soc_percent: float
  electricity_price_parameters:
    supplier_cost_import_eur_per_kwh: float
    supplier_cost_export_eur_per_kwh: float
    energy_tax_import_eur_per_kwh: float
    energy_tax_export_eur_per_kwh: float
    vat_import: float
    vat_export: float
  current_gross_consumption_power_entity: str
